name: canary_build
on: push

env:
  CI: true
  BROCCOLI_ENV: test
  NPM_AUTH_TOKEN: ${{ secrets.AUTOMATION_TOKEN }}
    
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        always-auth: true
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ./node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: list versions
      run: |
        node --version
        npm --version
        yarn --version
    - name: install dependencies
      run: | 
        echo "registry=https://registry.npmjs.org/" > ./.npmrc
        echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" >> ./.npmrc
        export PATH=$PATH:node_modules/.bin
        yarn
    - name: test
      run: |
        yarn test
